// Generated by SolidPython 1.1.1 on 2021-07-02 15:10:45


difference() {
	cube(size = [128, 86, 15]);
	translate(v = [0, 0, 3]) {
		translate(v = [10.0, 0, 0]) {
			translate(v = [0, 9.0, 0]) {
				cube(size = [108.0, 68.0, 50.0]);
			}
		}
	}
}