// Generated by SolidPython 1.1.1 on 2021-06-21 14:27:26


union() {
	translate(v = [11.0, 0, 0]) {
		translate(v = [0, 11.0, 0]) {
			cube(size = [128, 86, 15]);
		}
	}
	difference() {
		color(alpha = 1.0000000000, c = "red") {
			translate(v = [0, 0, 15]) {
				cube(size = [150.0, 108.0, 20]);
			}
		}
		translate(v = [0, 0, 20]) {
			translate(v = [5, 0, 0]) {
				translate(v = [0, 5, 0]) {
					cube(size = [140.0, 98.0, 25.0]);
				}
			}
		}
	}
}