// Generated by SolidPython 1.1.1 on 2021-06-16 14:58:23


difference() {
	cube(size = [128, 86, 15]);
	translate(v = [0, 0, 3]) {
		translate(v = [4.0000000000, 0, 0]) {
			translate(v = [0, 3.0000000000, 0]) {
				cube(size = [120, 80, 15.0]);
			}
		}
	}
}